# Generated by Django 3.0.4 on 2020-03-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bhindi',
            new_name='hunter',
        ),
    ]
